# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IB_PyQt_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1272, 924)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setSizeIncrement(QtCore.QSize(10, 10))
        MainWindow.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Images/IB.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setDockNestingEnabled(True)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowNestedDocks|QtWidgets.QMainWindow.AnimatedDocks|QtWidgets.QMainWindow.GroupedDragging)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        self.tabWidget.setMinimumSize(QtCore.QSize(300, 200))
        self.tabWidget.setObjectName("tabWidget")
        self.oneChart = QtWidgets.QWidget()
        self.oneChart.setObjectName("oneChart")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.oneChart)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.oneChartGraphicsView = QtWidgets.QGraphicsView(self.oneChart)
        self.oneChartGraphicsView.setObjectName("oneChartGraphicsView")
        self.verticalLayout_4.addWidget(self.oneChartGraphicsView)
        self.tabWidget.addTab(self.oneChart, "")
        self.multiChart = QtWidgets.QWidget()
        self.multiChart.setObjectName("multiChart")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.multiChart)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.multiChartMdiArea = QtWidgets.QMdiArea(self.multiChart)
        self.multiChartMdiArea.setObjectName("multiChartMdiArea")
        self.verticalLayout_5.addWidget(self.multiChartMdiArea)
        self.tabWidget.addTab(self.multiChart, "")
        self.tickerMonitor = QtWidgets.QWidget()
        self.tickerMonitor.setObjectName("tickerMonitor")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tickerMonitor)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tickerMonitorTableWidget = QtWidgets.QTableWidget(self.tickerMonitor)
        self.tickerMonitorTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tickerMonitorTableWidget.setShowGrid(True)
        self.tickerMonitorTableWidget.setGridStyle(QtCore.Qt.DashLine)
        self.tickerMonitorTableWidget.setWordWrap(True)
        self.tickerMonitorTableWidget.setObjectName("tickerMonitorTableWidget")
        self.tickerMonitorTableWidget.setColumnCount(9)
        self.tickerMonitorTableWidget.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tickerMonitorTableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tickerMonitorTableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tickerMonitorTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tickerMonitorTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tickerMonitorTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tickerMonitorTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tickerMonitorTableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tickerMonitorTableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tickerMonitorTableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tickerMonitorTableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tickerMonitorTableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tickerMonitorTableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tickerMonitorTableWidget.setItem(0, 1, item)
        self.tickerMonitorTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tickerMonitorTableWidget.horizontalHeader().setDefaultSectionSize(75)
        self.tickerMonitorTableWidget.horizontalHeader().setMinimumSectionSize(70)
        self.tickerMonitorTableWidget.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.tickerMonitorTableWidget)
        self.tabWidget.addTab(self.tickerMonitor, "")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_3.sizePolicy().hasHeightForWidth())
        self.tabWidget_3.setSizePolicy(sizePolicy)
        self.tabWidget_3.setMinimumSize(QtCore.QSize(300, 0))
        self.tabWidget_3.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.volumeTab = QtWidgets.QWidget()
        self.volumeTab.setObjectName("volumeTab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.volumeTab)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.volumeGraphicsView = QtWidgets.QGraphicsView(self.volumeTab)
        self.volumeGraphicsView.setObjectName("volumeGraphicsView")
        self.verticalLayout_6.addWidget(self.volumeGraphicsView)
        self.tabWidget_3.addTab(self.volumeTab, "")
        self.optionChainTab = QtWidgets.QWidget()
        self.optionChainTab.setObjectName("optionChainTab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.optionChainTab)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.optionChainTableWidget = QtWidgets.QTableWidget(self.optionChainTab)
        self.optionChainTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.optionChainTableWidget.setGridStyle(QtCore.Qt.DashLine)
        self.optionChainTableWidget.setObjectName("optionChainTableWidget")
        self.optionChainTableWidget.setColumnCount(10)
        self.optionChainTableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.optionChainTableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.optionChainTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.optionChainTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.optionChainTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.optionChainTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.optionChainTableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.optionChainTableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.optionChainTableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.optionChainTableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.optionChainTableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.optionChainTableWidget.setHorizontalHeaderItem(9, item)
        self.optionChainTableWidget.horizontalHeader().setDefaultSectionSize(70)
        self.optionChainTableWidget.horizontalHeader().setMinimumSectionSize(70)
        self.optionChainTableWidget.verticalHeader().setVisible(False)
        self.horizontalLayout.addWidget(self.optionChainTableWidget)
        self.tabWidget_3.addTab(self.optionChainTab, "")
        self.futureChainTab = QtWidgets.QWidget()
        self.futureChainTab.setObjectName("futureChainTab")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.futureChainTab)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.futureChainTableWidget = QtWidgets.QTableWidget(self.futureChainTab)
        self.futureChainTableWidget.setObjectName("futureChainTableWidget")
        self.futureChainTableWidget.setColumnCount(0)
        self.futureChainTableWidget.setRowCount(0)
        self.verticalLayout_19.addWidget(self.futureChainTableWidget)
        self.tabWidget_3.addTab(self.futureChainTab, "")
        self.verticalLayout_18.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1272, 26))
        self.menubar.setObjectName("menubar")
        self.menuLogin = QtWidgets.QMenu(self.menubar)
        self.menuLogin.setObjectName("menuLogin")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuWindow = QtWidgets.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        self.menuConfig = QtWidgets.QMenu(self.menubar)
        self.menuConfig.setObjectName("menuConfig")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.controlDockWidget = QtWidgets.QDockWidget(MainWindow)
        self.controlDockWidget.setMinimumSize(QtCore.QSize(250, 526))
        self.controlDockWidget.setMaximumSize(QtCore.QSize(250, 524287))
        self.controlDockWidget.setAcceptDrops(True)
        self.controlDockWidget.setWindowIcon(icon)
        self.controlDockWidget.setFloating(False)
        self.controlDockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea)
        self.controlDockWidget.setObjectName("controlDockWidget")
        self.controlDockWidgetContents = QtWidgets.QWidget()
        self.controlDockWidgetContents.setObjectName("controlDockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.controlDockWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.controlToolBox = QtWidgets.QToolBox(self.controlDockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controlToolBox.sizePolicy().hasHeightForWidth())
        self.controlToolBox.setSizePolicy(sizePolicy)
        self.controlToolBox.setMinimumSize(QtCore.QSize(250, 400))
        self.controlToolBox.setObjectName("controlToolBox")
        self.selectedTickerPage = QtWidgets.QWidget()
        self.selectedTickerPage.setEnabled(True)
        self.selectedTickerPage.setGeometry(QtCore.QRect(0, 0, 250, 702))
        self.selectedTickerPage.setObjectName("selectedTickerPage")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.selectedTickerPage)
        self.verticalLayout_10.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_10.setSpacing(3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.tickersGroupBox = QtWidgets.QGroupBox(self.selectedTickerPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tickersGroupBox.sizePolicy().hasHeightForWidth())
        self.tickersGroupBox.setSizePolicy(sizePolicy)
        self.tickersGroupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.tickersGroupBox.setObjectName("tickersGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.tickersGroupBox)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.tickerGroupComboBox = QtWidgets.QComboBox(self.tickersGroupBox)
        self.tickerGroupComboBox.setObjectName("tickerGroupComboBox")
        self.gridLayout.addWidget(self.tickerGroupComboBox, 0, 0, 1, 1)
        self.tickerGroupLineEdit = QtWidgets.QLineEdit(self.tickersGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tickerGroupLineEdit.sizePolicy().hasHeightForWidth())
        self.tickerGroupLineEdit.setSizePolicy(sizePolicy)
        self.tickerGroupLineEdit.setMinimumSize(QtCore.QSize(0, 28))
        self.tickerGroupLineEdit.setMaximumSize(QtCore.QSize(16777215, 28))
        self.tickerGroupLineEdit.setObjectName("tickerGroupLineEdit")
        self.gridLayout.addWidget(self.tickerGroupLineEdit, 1, 0, 1, 1)
        self.addTickerGroupButton = QtWidgets.QPushButton(self.tickersGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addTickerGroupButton.sizePolicy().hasHeightForWidth())
        self.addTickerGroupButton.setSizePolicy(sizePolicy)
        self.addTickerGroupButton.setMinimumSize(QtCore.QSize(20, 28))
        self.addTickerGroupButton.setMaximumSize(QtCore.QSize(16777215, 28))
        self.addTickerGroupButton.setObjectName("addTickerGroupButton")
        self.gridLayout.addWidget(self.addTickerGroupButton, 1, 1, 1, 1)
        self.loadTickerGroupButton = QtWidgets.QPushButton(self.tickersGroupBox)
        self.loadTickerGroupButton.setObjectName("loadTickerGroupButton")
        self.gridLayout.addWidget(self.loadTickerGroupButton, 0, 1, 1, 1)
        self.saveTickerGroupButton = QtWidgets.QPushButton(self.tickersGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveTickerGroupButton.sizePolicy().hasHeightForWidth())
        self.saveTickerGroupButton.setSizePolicy(sizePolicy)
        self.saveTickerGroupButton.setMinimumSize(QtCore.QSize(20, 28))
        self.saveTickerGroupButton.setMaximumSize(QtCore.QSize(16777215, 28))
        self.saveTickerGroupButton.setObjectName("saveTickerGroupButton")
        self.gridLayout.addWidget(self.saveTickerGroupButton, 3, 0, 1, 1)
        self.delTickerGroupButton = QtWidgets.QPushButton(self.tickersGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delTickerGroupButton.sizePolicy().hasHeightForWidth())
        self.delTickerGroupButton.setSizePolicy(sizePolicy)
        self.delTickerGroupButton.setMinimumSize(QtCore.QSize(0, 28))
        self.delTickerGroupButton.setMaximumSize(QtCore.QSize(16777215, 28))
        self.delTickerGroupButton.setObjectName("delTickerGroupButton")
        self.gridLayout.addWidget(self.delTickerGroupButton, 3, 1, 1, 1)
        self.verticalLayout_10.addWidget(self.tickersGroupBox)
        self.tickerListBox = QtWidgets.QGroupBox(self.selectedTickerPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tickerListBox.sizePolicy().hasHeightForWidth())
        self.tickerListBox.setSizePolicy(sizePolicy)
        self.tickerListBox.setAlignment(QtCore.Qt.AlignCenter)
        self.tickerListBox.setObjectName("tickerListBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tickerListBox)
        self.gridLayout_3.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_3.setSpacing(5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tickerListLineEdit = QtWidgets.QLineEdit(self.tickerListBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tickerListLineEdit.sizePolicy().hasHeightForWidth())
        self.tickerListLineEdit.setSizePolicy(sizePolicy)
        self.tickerListLineEdit.setMinimumSize(QtCore.QSize(0, 28))
        self.tickerListLineEdit.setMaximumSize(QtCore.QSize(16777215, 28))
        self.tickerListLineEdit.setObjectName("tickerListLineEdit")
        self.gridLayout_3.addWidget(self.tickerListLineEdit, 1, 0, 1, 1)
        self.addTickerListButton = QtWidgets.QPushButton(self.tickerListBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addTickerListButton.sizePolicy().hasHeightForWidth())
        self.addTickerListButton.setSizePolicy(sizePolicy)
        self.addTickerListButton.setMinimumSize(QtCore.QSize(20, 28))
        self.addTickerListButton.setMaximumSize(QtCore.QSize(16777215, 28))
        self.addTickerListButton.setObjectName("addTickerListButton")
        self.gridLayout_3.addWidget(self.addTickerListButton, 1, 1, 1, 1)
        self.saveTickerListButton = QtWidgets.QPushButton(self.tickerListBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveTickerListButton.sizePolicy().hasHeightForWidth())
        self.saveTickerListButton.setSizePolicy(sizePolicy)
        self.saveTickerListButton.setMinimumSize(QtCore.QSize(20, 28))
        self.saveTickerListButton.setMaximumSize(QtCore.QSize(16777215, 28))
        self.saveTickerListButton.setObjectName("saveTickerListButton")
        self.gridLayout_3.addWidget(self.saveTickerListButton, 2, 0, 1, 1)
        self.delTickerListButton = QtWidgets.QPushButton(self.tickerListBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delTickerListButton.sizePolicy().hasHeightForWidth())
        self.delTickerListButton.setSizePolicy(sizePolicy)
        self.delTickerListButton.setMinimumSize(QtCore.QSize(0, 28))
        self.delTickerListButton.setMaximumSize(QtCore.QSize(16777215, 28))
        self.delTickerListButton.setObjectName("delTickerListButton")
        self.gridLayout_3.addWidget(self.delTickerListButton, 2, 1, 1, 1)
        self.tickerListTableWidget = QtWidgets.QTableWidget(self.tickerListBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tickerListTableWidget.sizePolicy().hasHeightForWidth())
        self.tickerListTableWidget.setSizePolicy(sizePolicy)
        self.tickerListTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tickerListTableWidget.setGridStyle(QtCore.Qt.DashLine)
        self.tickerListTableWidget.setRowCount(3)
        self.tickerListTableWidget.setObjectName("tickerListTableWidget")
        self.tickerListTableWidget.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tickerListTableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tickerListTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tickerListTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tickerListTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tickerListTableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tickerListTableWidget.setItem(0, 1, item)
        self.tickerListTableWidget.horizontalHeader().setDefaultSectionSize(75)
        self.tickerListTableWidget.horizontalHeader().setMinimumSectionSize(70)
        self.tickerListTableWidget.verticalHeader().setVisible(False)
        self.gridLayout_3.addWidget(self.tickerListTableWidget, 0, 0, 1, 2)
        self.verticalLayout_10.addWidget(self.tickerListBox)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Images/triangle_up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.controlToolBox.addItem(self.selectedTickerPage, icon1, "")
        self.futureStrategyPage = QtWidgets.QWidget()
        self.futureStrategyPage.setGeometry(QtCore.QRect(0, 0, 250, 702))
        self.futureStrategyPage.setObjectName("futureStrategyPage")
        self.controlToolBox.addItem(self.futureStrategyPage, icon1, "")
        self.optionStrategyPage = QtWidgets.QWidget()
        self.optionStrategyPage.setGeometry(QtCore.QRect(0, 0, 250, 702))
        self.optionStrategyPage.setObjectName("optionStrategyPage")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.optionStrategyPage)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.optionStrategyGroupBox = QtWidgets.QGroupBox(self.optionStrategyPage)
        self.optionStrategyGroupBox.setObjectName("optionStrategyGroupBox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.optionStrategyGroupBox)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.optionStrategyComboBox = QtWidgets.QComboBox(self.optionStrategyGroupBox)
        self.optionStrategyComboBox.setObjectName("optionStrategyComboBox")
        self.optionStrategyComboBox.addItem("")
        self.optionStrategyComboBox.addItem("")
        self.optionStrategyComboBox.addItem("")
        self.optionStrategyComboBox.addItem("")
        self.optionStrategyComboBox.addItem("")
        self.verticalLayout_8.addWidget(self.optionStrategyComboBox)
        self.verticalLayout_9.addWidget(self.optionStrategyGroupBox)
        self.controlToolBox.addItem(self.optionStrategyPage, icon1, "")
        self.verticalLayout.addWidget(self.controlToolBox)
        self.controlDockWidget.setWidget(self.controlDockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.controlDockWidget)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy)
        self.dockWidget.setMinimumSize(QtCore.QSize(310, 500))
        self.dockWidget.setMaximumSize(QtCore.QSize(310, 524287))
        self.dockWidget.setAcceptDrops(True)
        self.dockWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dockWidget.setFloating(False)
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.dockWidget.setAllowedAreas(QtCore.Qt.RightDockWidgetArea)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.dockWidgetContents)
        self.tabWidget_2.setAcceptDrops(True)
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget_2.setMovable(True)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.accountTab = QtWidgets.QWidget()
        self.accountTab.setObjectName("accountTab")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.accountTab)
        self.verticalLayout_14.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_14.setSpacing(3)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.accountGroupBox = QtWidgets.QGroupBox(self.accountTab)
        self.accountGroupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.accountGroupBox.setObjectName("accountGroupBox")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.accountGroupBox)
        self.verticalLayout_13.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.accountTableWidget = QtWidgets.QTableWidget(self.accountGroupBox)
        self.accountTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.accountTableWidget.setShowGrid(True)
        self.accountTableWidget.setRowCount(7)
        self.accountTableWidget.setColumnCount(1)
        self.accountTableWidget.setObjectName("accountTableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.accountTableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.accountTableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.accountTableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.accountTableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.accountTableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.accountTableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.accountTableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.accountTableWidget.setHorizontalHeaderItem(0, item)
        self.accountTableWidget.horizontalHeader().setVisible(False)
        self.verticalLayout_13.addWidget(self.accountTableWidget)
        self.verticalLayout_14.addWidget(self.accountGroupBox)
        self.portfolioGroupBox = QtWidgets.QGroupBox(self.accountTab)
        self.portfolioGroupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.portfolioGroupBox.setObjectName("portfolioGroupBox")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.portfolioGroupBox)
        self.verticalLayout_12.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.portfolioTableWidget = QtWidgets.QTableWidget(self.portfolioGroupBox)
        self.portfolioTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.portfolioTableWidget.setObjectName("portfolioTableWidget")
        self.portfolioTableWidget.setColumnCount(5)
        self.portfolioTableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.portfolioTableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.portfolioTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.portfolioTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.portfolioTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.portfolioTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.portfolioTableWidget.setHorizontalHeaderItem(4, item)
        self.portfolioTableWidget.horizontalHeader().setDefaultSectionSize(70)
        self.portfolioTableWidget.horizontalHeader().setHighlightSections(True)
        self.portfolioTableWidget.verticalHeader().setVisible(False)
        self.verticalLayout_12.addWidget(self.portfolioTableWidget)
        self.verticalLayout_14.addWidget(self.portfolioGroupBox)
        self.tabWidget_2.addTab(self.accountTab, "")
        self.tradingTab = QtWidgets.QWidget()
        self.tradingTab.setObjectName("tradingTab")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.tradingTab)
        self.verticalLayout_17.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_17.setSpacing(3)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.tradingOrdersGroupBox = QtWidgets.QGroupBox(self.tradingTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tradingOrdersGroupBox.sizePolicy().hasHeightForWidth())
        self.tradingOrdersGroupBox.setSizePolicy(sizePolicy)
        self.tradingOrdersGroupBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.tradingOrdersGroupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.tradingOrdersGroupBox.setObjectName("tradingOrdersGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tradingOrdersGroupBox)
        self.verticalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.askBidTableWidget = QtWidgets.QTableWidget(self.tradingOrdersGroupBox)
        self.askBidTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.askBidTableWidget.setGridStyle(QtCore.Qt.DashLine)
        self.askBidTableWidget.setObjectName("askBidTableWidget")
        self.askBidTableWidget.setColumnCount(4)
        self.askBidTableWidget.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.askBidTableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.askBidTableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.askBidTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.askBidTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.askBidTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.askBidTableWidget.setHorizontalHeaderItem(3, item)
        self.askBidTableWidget.horizontalHeader().setDefaultSectionSize(60)
        self.askBidTableWidget.horizontalHeader().setMinimumSectionSize(50)
        self.askBidTableWidget.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.askBidTableWidget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.orderTypeComboBox = QtWidgets.QComboBox(self.tradingOrdersGroupBox)
        self.orderTypeComboBox.setMaxVisibleItems(5)
        self.orderTypeComboBox.setObjectName("orderTypeComboBox")
        self.orderTypeComboBox.addItem("")
        self.orderTypeComboBox.addItem("")
        self.orderTypeComboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.orderTypeComboBox)
        self.priceLineEdit = QtWidgets.QLineEdit(self.tradingOrdersGroupBox)
        self.priceLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.priceLineEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.priceLineEdit.setObjectName("priceLineEdit")
        self.horizontalLayout_3.addWidget(self.priceLineEdit)
        self.orderNumComboBox = QtWidgets.QComboBox(self.tradingOrdersGroupBox)
        self.orderNumComboBox.setEditable(False)
        self.orderNumComboBox.setObjectName("orderNumComboBox")
        self.orderNumComboBox.addItem("")
        self.orderNumComboBox.addItem("")
        self.orderNumComboBox.addItem("")
        self.orderNumComboBox.addItem("")
        self.orderNumComboBox.addItem("")
        self.orderNumComboBox.addItem("")
        self.orderNumComboBox.addItem("")
        self.orderNumComboBox.addItem("")
        self.orderNumComboBox.addItem("")
        self.orderNumComboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.orderNumComboBox)
        self.orderNumLineEdit = QtWidgets.QLineEdit(self.tradingOrdersGroupBox)
        self.orderNumLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.orderNumLineEdit.setObjectName("orderNumLineEdit")
        self.horizontalLayout_3.addWidget(self.orderNumLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.buyPushButton = QtWidgets.QPushButton(self.tradingOrdersGroupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.buyPushButton.setFont(font)
        self.buyPushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buyPushButton.setObjectName("buyPushButton")
        self.horizontalLayout_2.addWidget(self.buyPushButton)
        self.sellPushButton = QtWidgets.QPushButton(self.tradingOrdersGroupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.sellPushButton.setFont(font)
        self.sellPushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sellPushButton.setObjectName("sellPushButton")
        self.horizontalLayout_2.addWidget(self.sellPushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_17.addWidget(self.tradingOrdersGroupBox)
        self.pendingOrderGroupBox = QtWidgets.QGroupBox(self.tradingTab)
        self.pendingOrderGroupBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.pendingOrderGroupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.pendingOrderGroupBox.setObjectName("pendingOrderGroupBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.pendingOrderGroupBox)
        self.verticalLayout_7.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_7.setSpacing(3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pendingOrdersTableView = QtWidgets.QTableView(self.pendingOrderGroupBox)
        self.pendingOrdersTableView.setGridStyle(QtCore.Qt.DashLine)
        self.pendingOrdersTableView.setObjectName("pendingOrdersTableView")
        self.verticalLayout_7.addWidget(self.pendingOrdersTableView)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.orderQuantityLineEdit = QtWidgets.QLineEdit(self.pendingOrderGroupBox)
        self.orderQuantityLineEdit.setObjectName("orderQuantityLineEdit")
        self.horizontalLayout_4.addWidget(self.orderQuantityLineEdit)
        self.orderPricePushButton = QtWidgets.QPushButton(self.pendingOrderGroupBox)
        self.orderPricePushButton.setMaximumSize(QtCore.QSize(70, 16777215))
        self.orderPricePushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.orderPricePushButton.setObjectName("orderPricePushButton")
        self.horizontalLayout_4.addWidget(self.orderPricePushButton)
        self.orderPriceLineEdit = QtWidgets.QLineEdit(self.pendingOrderGroupBox)
        self.orderPriceLineEdit.setObjectName("orderPriceLineEdit")
        self.horizontalLayout_4.addWidget(self.orderPriceLineEdit)
        self.orderPricePushButton_2 = QtWidgets.QPushButton(self.pendingOrderGroupBox)
        self.orderPricePushButton_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.orderPricePushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.orderPricePushButton_2.setObjectName("orderPricePushButton_2")
        self.horizontalLayout_4.addWidget(self.orderPricePushButton_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.updatePushButton = QtWidgets.QPushButton(self.pendingOrderGroupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.updatePushButton.setFont(font)
        self.updatePushButton.setObjectName("updatePushButton")
        self.horizontalLayout_5.addWidget(self.updatePushButton)
        self.cancelPushButton = QtWidgets.QPushButton(self.pendingOrderGroupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.cancelPushButton.setFont(font)
        self.cancelPushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.horizontalLayout_5.addWidget(self.cancelPushButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.verticalLayout_17.addWidget(self.pendingOrderGroupBox)
        self.tabWidget_2.addTab(self.tradingTab, "")
        self.verticalLayout_16.addWidget(self.tabWidget_2)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget)
        self.actionConnect = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Images/connect.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConnect.setIcon(icon2)
        self.actionConnect.setObjectName("actionConnect")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Images/ib-logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionAbout.setIcon(icon3)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAbout_QT = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Images/Qt.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/Images/Qt.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionAbout_QT.setIcon(icon4)
        self.actionAbout_QT.setObjectName("actionAbout_QT")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Images/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionOpen.setIcon(icon5)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Images/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionSave.setIcon(icon6)
        self.actionSave.setObjectName("actionSave")
        self.actionLogin_to_account = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Images/Login.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLogin_to_account.setIcon(icon7)
        self.actionLogin_to_account.setObjectName("actionLogin_to_account")
        self.actionNew = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Images/new.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionNew.setIcon(icon8)
        self.actionNew.setObjectName("actionNew")
        self.actionTest_Connection = QtWidgets.QAction(MainWindow)
        self.actionTest_Connection.setObjectName("actionTest_Connection")
        self.actionZoom_In = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Images/Zoom-In-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_In.setIcon(icon9)
        self.actionZoom_In.setObjectName("actionZoom_In")
        self.actionZoom_Out = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/Images/Zoom-Out-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_Out.setIcon(icon10)
        self.actionZoom_Out.setObjectName("actionZoom_Out")
        self.actionControl = QtWidgets.QAction(MainWindow)
        self.actionControl.setCheckable(True)
        self.actionControl.setChecked(True)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/Images/control.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionControl.setIcon(icon11)
        self.actionControl.setObjectName("actionControl")
        self.actionAccount = QtWidgets.QAction(MainWindow)
        self.actionAccount.setCheckable(True)
        self.actionAccount.setChecked(True)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/Images/Account.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAccount.setIcon(icon12)
        self.actionAccount.setObjectName("actionAccount")
        self.actionTrading = QtWidgets.QAction(MainWindow)
        self.actionTrading.setCheckable(True)
        self.actionTrading.setChecked(True)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/Images/Trading.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTrading.setIcon(icon13)
        self.actionTrading.setObjectName("actionTrading")
        self.actionGet_Data_From_Quandl = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/Images/Quandl.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGet_Data_From_Quandl.setIcon(icon14)
        self.actionGet_Data_From_Quandl.setObjectName("actionGet_Data_From_Quandl")
        self.actionGet_Data_From_Local_Database = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/Images/database.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGet_Data_From_Local_Database.setIcon(icon15)
        self.actionGet_Data_From_Local_Database.setObjectName("actionGet_Data_From_Local_Database")
        self.actionCandelsticks_Plot = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/Images/Candelsticks.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCandelsticks_Plot.setIcon(icon16)
        self.actionCandelsticks_Plot.setObjectName("actionCandelsticks_Plot")
        self.actionLine_Plot = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/Images/Line.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLine_Plot.setIcon(icon17)
        self.actionLine_Plot.setObjectName("actionLine_Plot")
        self.actionTick_Plot = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/Images/tick.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTick_Plot.setIcon(icon18)
        self.actionTick_Plot.setObjectName("actionTick_Plot")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/Images/quit.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon19)
        self.actionQuit.setObjectName("actionQuit")
        self.actionOption_Chain = QtWidgets.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/Images/option.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOption_Chain.setIcon(icon20)
        self.actionOption_Chain.setObjectName("actionOption_Chain")
        self.actionFuture_Chain = QtWidgets.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/Images/future.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFuture_Chain.setIcon(icon21)
        self.actionFuture_Chain.setObjectName("actionFuture_Chain")
        self.actionOne_Chart = QtWidgets.QAction(MainWindow)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/Images/chart.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOne_Chart.setIcon(icon22)
        self.actionOne_Chart.setObjectName("actionOne_Chart")
        self.menuLogin.addAction(self.actionConnect)
        self.menuLogin.addAction(self.actionLogin_to_account)
        self.menuLogin.addSeparator()
        self.menuLogin.addAction(self.actionGet_Data_From_Quandl)
        self.menuLogin.addAction(self.actionGet_Data_From_Local_Database)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout_QT)
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuView.addAction(self.actionZoom_In)
        self.menuView.addAction(self.actionZoom_Out)
        self.menuView.addAction(self.actionCandelsticks_Plot)
        self.menuView.addAction(self.actionLine_Plot)
        self.menuView.addAction(self.actionTick_Plot)
        self.menuWindow.addAction(self.actionControl)
        self.menuWindow.addAction(self.actionAccount)
        self.menuWindow.addAction(self.actionTrading)
        self.menuConfig.addAction(self.actionOption_Chain)
        self.menuConfig.addAction(self.actionFuture_Chain)
        self.menuConfig.addAction(self.actionOne_Chart)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuLogin.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuConfig.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionQuit)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionZoom_In)
        self.toolBar.addAction(self.actionZoom_Out)
        self.toolBar.addAction(self.actionCandelsticks_Plot)
        self.toolBar.addAction(self.actionLine_Plot)
        self.toolBar.addAction(self.actionTick_Plot)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionControl)
        self.toolBar.addAction(self.actionAccount)
        self.toolBar.addAction(self.actionTrading)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionConnect)
        self.toolBar.addAction(self.actionLogin_to_account)
        self.toolBar.addAction(self.actionGet_Data_From_Quandl)
        self.toolBar.addAction(self.actionGet_Data_From_Local_Database)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionOne_Chart)
        self.toolBar.addAction(self.actionOption_Chain)
        self.toolBar.addAction(self.actionFuture_Chain)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.controlToolBox.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.actionQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "IB_PyQt"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.oneChart), _translate("MainWindow", "One-Chart"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.multiChart), _translate("MainWindow", "Multi-Chart"))
        item = self.tickerMonitorTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Symbol"))
        item = self.tickerMonitorTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Last"))
        item = self.tickerMonitorTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "%Change"))
        item = self.tickerMonitorTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Net Chng"))
        item = self.tickerMonitorTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Bid"))
        item = self.tickerMonitorTableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Ask"))
        item = self.tickerMonitorTableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Volume"))
        item = self.tickerMonitorTableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "MTD"))
        item = self.tickerMonitorTableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "YTD"))
        __sortingEnabled = self.tickerMonitorTableWidget.isSortingEnabled()
        self.tickerMonitorTableWidget.setSortingEnabled(False)
        self.tickerMonitorTableWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tickerMonitor), _translate("MainWindow", "Ticker Monitor"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.volumeTab), _translate("MainWindow", "Volume"))
        item = self.optionChainTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Impl Vol."))
        item = self.optionChainTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Delta"))
        item = self.optionChainTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Bid"))
        item = self.optionChainTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Ask"))
        item = self.optionChainTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Exp"))
        item = self.optionChainTableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Strike"))
        item = self.optionChainTableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Bid"))
        item = self.optionChainTableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Ask"))
        item = self.optionChainTableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Impl Vol."))
        item = self.optionChainTableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Delta"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.optionChainTab), _translate("MainWindow", "Option Chain"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.futureChainTab), _translate("MainWindow", "Future Chain"))
        self.menuLogin.setTitle(_translate("MainWindow", "Login"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuWindow.setTitle(_translate("MainWindow", "Window"))
        self.menuConfig.setTitle(_translate("MainWindow", "Config"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.controlDockWidget.setWindowTitle(_translate("MainWindow", "Control"))
        self.tickersGroupBox.setTitle(_translate("MainWindow", "Tickers Group"))
        self.addTickerGroupButton.setText(_translate("MainWindow", "Add Group"))
        self.loadTickerGroupButton.setText(_translate("MainWindow", "Load Group"))
        self.saveTickerGroupButton.setText(_translate("MainWindow", "Save Group"))
        self.delTickerGroupButton.setText(_translate("MainWindow", "Delete Group"))
        self.tickerListBox.setTitle(_translate("MainWindow", "Tickers List"))
        self.addTickerListButton.setText(_translate("MainWindow", "Add Ticker"))
        self.saveTickerListButton.setText(_translate("MainWindow", "Save Ticker"))
        self.delTickerListButton.setText(_translate("MainWindow", "Delete Ticker"))
        item = self.tickerListTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Symbol"))
        item = self.tickerListTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Last"))
        item = self.tickerListTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "%Change"))
        __sortingEnabled = self.tickerListTableWidget.isSortingEnabled()
        self.tickerListTableWidget.setSortingEnabled(False)
        self.tickerListTableWidget.setSortingEnabled(__sortingEnabled)
        self.controlToolBox.setItemText(self.controlToolBox.indexOf(self.selectedTickerPage), _translate("MainWindow", "Selected Tickers"))
        self.controlToolBox.setItemText(self.controlToolBox.indexOf(self.futureStrategyPage), _translate("MainWindow", "Futures Strategy"))
        self.optionStrategyGroupBox.setTitle(_translate("MainWindow", "Option Strategy"))
        self.optionStrategyComboBox.setItemText(0, _translate("MainWindow", "Select a Strategy"))
        self.optionStrategyComboBox.setItemText(1, _translate("MainWindow", "Vertical Spread"))
        self.optionStrategyComboBox.setItemText(2, _translate("MainWindow", "Calender Spread"))
        self.optionStrategyComboBox.setItemText(3, _translate("MainWindow", "Iron Condor Strategy"))
        self.optionStrategyComboBox.setItemText(4, _translate("MainWindow", "Butterfly Strategy"))
        self.controlToolBox.setItemText(self.controlToolBox.indexOf(self.optionStrategyPage), _translate("MainWindow", "Option Strategy"))
        self.accountGroupBox.setTitle(_translate("MainWindow", "Account"))
        item = self.accountTableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "User Name"))
        item = self.accountTableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Capital Used"))
        item = self.accountTableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Cash"))
        item = self.accountTableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "PNL"))
        item = self.accountTableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Portfolio Value"))
        item = self.accountTableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Position Value"))
        item = self.accountTableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Returns"))
        self.portfolioGroupBox.setTitle(_translate("MainWindow", "Portfolio"))
        item = self.portfolioTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Symbol"))
        item = self.portfolioTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Amount"))
        item = self.portfolioTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Cost"))
        item = self.portfolioTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Last Price"))
        item = self.portfolioTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "PNL"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.accountTab), _translate("MainWindow", "Account Overview"))
        self.tradingOrdersGroupBox.setTitle(_translate("MainWindow", "Trading Orders"))
        item = self.askBidTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Num"))
        item = self.askBidTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Bid"))
        item = self.askBidTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Ask"))
        item = self.askBidTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Num"))
        self.orderTypeComboBox.setCurrentText(_translate("MainWindow", "LMT"))
        self.orderTypeComboBox.setItemText(0, _translate("MainWindow", "LMT"))
        self.orderTypeComboBox.setItemText(1, _translate("MainWindow", "MKT"))
        self.orderTypeComboBox.setItemText(2, _translate("MainWindow", "STL"))
        self.orderNumComboBox.setCurrentText(_translate("MainWindow", "Num"))
        self.orderNumComboBox.setItemText(0, _translate("MainWindow", "Num"))
        self.orderNumComboBox.setItemText(1, _translate("MainWindow", "1"))
        self.orderNumComboBox.setItemText(2, _translate("MainWindow", "2"))
        self.orderNumComboBox.setItemText(3, _translate("MainWindow", "5"))
        self.orderNumComboBox.setItemText(4, _translate("MainWindow", "10"))
        self.orderNumComboBox.setItemText(5, _translate("MainWindow", "100"))
        self.orderNumComboBox.setItemText(6, _translate("MainWindow", "200"))
        self.orderNumComboBox.setItemText(7, _translate("MainWindow", "500"))
        self.orderNumComboBox.setItemText(8, _translate("MainWindow", "1000"))
        self.orderNumComboBox.setItemText(9, _translate("MainWindow", "Other"))
        self.buyPushButton.setText(_translate("MainWindow", "BUY"))
        self.sellPushButton.setText(_translate("MainWindow", "SELL"))
        self.pendingOrderGroupBox.setTitle(_translate("MainWindow", "Pending Orders"))
        self.orderPricePushButton.setText(_translate("MainWindow", "Quantity"))
        self.orderPricePushButton_2.setText(_translate("MainWindow", "Price"))
        self.updatePushButton.setText(_translate("MainWindow", "Update Order"))
        self.cancelPushButton.setText(_translate("MainWindow", "Cancel Order"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tradingTab), _translate("MainWindow", "Trading"))
        self.actionConnect.setText(_translate("MainWindow", "Connect To IB"))
        self.actionAbout.setText(_translate("MainWindow", "About IB_PyQt"))
        self.actionAbout_QT.setText(_translate("MainWindow", "About QT"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionLogin_to_account.setText(_translate("MainWindow", "Login To Your Account"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionTest_Connection.setText(_translate("MainWindow", "Test Connection With IB"))
        self.actionZoom_In.setText(_translate("MainWindow", "Zoom In"))
        self.actionZoom_Out.setText(_translate("MainWindow", "Zoom Out"))
        self.actionControl.setText(_translate("MainWindow", "Control"))
        self.actionAccount.setText(_translate("MainWindow", "Account Overview"))
        self.actionTrading.setText(_translate("MainWindow", "Trading"))
        self.actionGet_Data_From_Quandl.setText(_translate("MainWindow", "Get Data From Quandl"))
        self.actionGet_Data_From_Local_Database.setText(_translate("MainWindow", "Connect to Local Database"))
        self.actionCandelsticks_Plot.setText(_translate("MainWindow", "Candlesticks Plot"))
        self.actionLine_Plot.setText(_translate("MainWindow", "Line Chart Plot"))
        self.actionTick_Plot.setText(_translate("MainWindow", "Tick Chart Plot"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionOption_Chain.setText(_translate("MainWindow", "Option Chain"))
        self.actionFuture_Chain.setText(_translate("MainWindow", "Future Chain"))
        self.actionOne_Chart.setText(_translate("MainWindow", "One Chart"))

import resource_rc
